- name: installer des programmes utiles avec apt
  hosts: localhost
  become: yes
  become_user: root
  vars:
     server_name: localhost
  tasks:
    - name: ensure latest version of main tools for desktop is installed
      apt:
        state: present
        name:
          - arp-scan
          - audacity
          - baobab
          - borgbackup
          - curl
          - docker
          - dolphin
          - thunar
          - docker-compose
          - etckeeper
          - gajim
          - geeqie
          - gimp
          - git
          - gpa
          - gnupg
          - grsync
          - jq
          - kdenlive
          - keepassxc
          - konsole
          - krita
          - krita-l10n
          - meld
          - nano
          - ncdu
          - nginx
          - npm
          - pandoc
          - php
          - python3
          - python3-pip
          - terminator
          - tig
          - transmission
          - ufw
          - zsh
          - veracrypt
          - testdisk
          - htop
          - btop
          - python3-pip
          - python3-setuptools
          - autopostgresqlbackup
          - automysqlbackup
          - certbot
          - smartmontools
          - fail2ban
          - snapd
          - unattended-upgrades
          - php
          - php-fpm
          - php-xml
          - php-mysql
          - rsync
          - php-dom
          - php-curl
          - vrms
          - klavaro
